### ISSUE TITLE
Add UUIDs to assets

### ISSUE THREAD

**Issue by stam** [eye2web/tank-server#1]
On the frontend I would like to keep track of assets (tanks/lasers/explosions) and not delete and recreate them every tick to add performance.

Tanks have IDs, but they are not unique, if a tank is killed and a new tank joins, they get the same ID but they are not the same instance. (movement between a killed tank and a newly joined tank in the next tick should not a animated).

Add UUIDs for unique instances of lasers/trees/tanks/explosions

**Comment by eye2web** [comment]
#3
